<template>
  <div class="app-container">

    <!-- Particle canvas background -->
    <canvas class="particle-canvas" ref="particleCanvas"></canvas>
    <!-- Grid overlay -->
    <div class="grid-overlay"></div>

    <main class="content-wrapper">
      <transition name="view-transition" mode="out-in" :key="view">

        <!-- ══════════════════════════════════════════
             1. LANDING PAGE
        ══════════════════════════════════════════ -->
        <div v-if="view === 'landing'" class="view-container landing-view" key="landing">

          <!-- Top nav bar -->
          <nav class="top-nav">
            <div class="nav-logo">
              <span class="logo-dot"></span>
              <span>NexCV</span>
              <span class="nav-version">v2.0</span>
            </div>
            <div class="nav-links">
              <span class="nav-tag">Powered by Claude</span>
            </div>
          </nav>

          <!-- Hero section -->
          <div class="hero-section">
            <div class="hero-badge">
              <span class="badge-pulse"></span>
              ATS-OPTIMIZED · AI-GENERATED · ELITE FORMAT
            </div>

            <h1 class="hero-headline">
              <span class="line-reveal" style="--delay: 0.1s">Engineer Your</span>
              <span class="line-reveal gradient-line" style="--delay: 0.25s">Professional</span>
              <span class="line-reveal gradient-line" style="--delay: 0.4s">Identity.</span>
            </h1>

            <p class="hero-sub line-reveal" style="--delay: 0.55s">
              Elite resumes generated by AI. Designed to pass ATS filters and land top-tier tech roles.
            </p>

            <!-- Feature chips -->
            <div class="feature-chips line-reveal" style="--delay: 0.7s">
              <span class="chip"><span class="chip-icon">◈</span> AI Expansion</span>
              <span class="chip"><span class="chip-icon">◈</span> Harvard Format</span>
              <span class="chip"><span class="chip-icon">◈</span> ATS Optimized</span>
              <span class="chip"><span class="chip-icon">◈</span> PDF Export</span>
            </div>

            <!-- CTA -->
            <div class="cta-block line-reveal" style="--delay: 0.85s">
              <button class="cta-primary" @click="view = 'form'">
                <span class="cta-text">Build My CV</span>
                <span class="cta-arrow">→</span>
                <span class="cta-shimmer"></span>
              </button>
              <span class="cta-note">No account needed · Takes ~3 minutes</span>
            </div>
          </div>

          <!-- Floating preview card -->
          <div class="preview-float line-reveal" style="--delay: 1s">
            <div class="preview-card">
              <div class="preview-header">
                <div class="preview-avatar">AM</div>
                <div>
                  <div class="preview-name">Alexander Mercer</div>
                  <div class="preview-role">Staff Engineer · OpenAI</div>
                </div>
                <div class="preview-score">
                  <div class="score-ring">
                    <svg viewBox="0 0 36 36" class="ring-svg">
                      <circle cx="18" cy="18" r="15" fill="none" stroke="rgba(255,255,255,0.1)" stroke-width="3"/>
                      <circle cx="18" cy="18" r="15" fill="none" stroke="#fff" stroke-width="3"
                        stroke-dasharray="94 100" stroke-dashoffset="25" stroke-linecap="round"/>
                    </svg>
                    <span class="score-num">94</span>
                  </div>
                  <span class="score-label">ATS</span>
                </div>
              </div>
              <div class="preview-skills">
                <span class="skill-tag">Python</span>
                <span class="skill-tag">Go</span>
                <span class="skill-tag">Kubernetes</span>
                <span class="skill-tag">AWS</span>
                <span class="skill-tag active">+6 more</span>
              </div>
              <div class="preview-bars">
                <div class="bar-row">
                  <span>Experience</span>
                  <div class="bar-track"><div class="bar-fill" style="width:92%"></div></div>
                </div>
                <div class="bar-row">
                  <span>Projects</span>
                  <div class="bar-track"><div class="bar-fill" style="width:78%"></div></div>
                </div>
                <div class="bar-row">
                  <span>Keywords</span>
                  <div class="bar-track"><div class="bar-fill" style="width:96%"></div></div>
                </div>
              </div>
            </div>
            <div class="preview-glow"></div>
          </div>

          <!-- Stats row -->
          <div class="stats-row line-reveal" style="--delay: 1.1s">
            <div class="stat-item">
              <span class="stat-num">12K+</span>
              <span class="stat-label">CVs Generated</span>
            </div>
            <div class="stat-divider"></div>
            <div class="stat-item">
              <span class="stat-num">94%</span>
              <span class="stat-label">ATS Pass Rate</span>
            </div>
            <div class="stat-divider"></div>
            <div class="stat-item">
              <span class="stat-num">< 60s</span>
              <span class="stat-label">Generation Time</span>
            </div>
          </div>

        </div>

        <!-- ══════════════════════════════════════════
             2. FORM PAGE
        ══════════════════════════════════════════ -->
        <div v-else-if="view === 'form'" class="view-container form-view" key="form">

          <div class="form-topbar">
            <button class="back-btn" @click="view = 'landing'">
              <span class="back-arrow">←</span> Back
            </button>
            <div class="form-progress">
              <span class="progress-label">CV Builder</span>
              <div class="progress-dots">
                <span class="pdot active"></span>
                <span class="pdot active"></span>
                <span class="pdot"></span>
              </div>
            </div>
            <button type="button" class="btn-load-demo" @click="fillDummyData">⚡ Load Demo</button>
          </div>

          <div class="form-hero-text">
            <h2>Architect Your <span class="text-accent">CV</span></h2>
            <p>Fill in your details — our AI will expand, enhance and optimize everything.</p>
          </div>

          <form @submit.prevent="submitForm" class="cv-form">

            <!-- ── Personal Info ── -->
            <section class="form-section">
              <div class="section-label">
                <span class="section-num">01</span>
                <h3>Personal Details</h3>
              </div>
              <div class="input-grid-2">
                <div class="input-group">
                  <label>Full Name</label>
                  <input v-model="formData.name" required placeholder="Jane Smith" />
                </div>
                <div class="input-group">
                  <label>Email</label>
                  <input v-model="formData.email" type="email" placeholder="jane@email.com" />
                </div>
                <div class="input-group">
                  <label>Phone</label>
                  <input v-model="formData.phone" placeholder="+1 (555) 000-0000" />
                </div>
                <div class="input-group">
                  <label>Links (LinkedIn / GitHub)</label>
                  <input v-model="formData.links" placeholder="linkedin.com/in/jane" />
                </div>
              </div>
              <div class="input-group mt-3">
                <label>Professional Summary <span class="label-hint">AI will expand this</span></label>
                <textarea v-model="formData.summary" rows="3" placeholder="e.g. Full-stack engineer with 5 years experience in distributed systems..."></textarea>
              </div>
              <div class="input-group mt-2">
                <label>Technical Skills</label>
                <textarea v-model="formData.skills" rows="2" placeholder="Python, React, AWS, Docker, PostgreSQL..."></textarea>
              </div>
            </section>

            <!-- ── Experience ── -->
            <section class="form-section">
              <div class="section-label">
                <span class="section-num">02</span>
                <h3>Experience</h3>
                <button type="button" class="btn-add" @click="addExperience">+ Add Role</button>
              </div>
              <transition-group name="block-anim" tag="div">
                <div v-for="(exp, index) in formData.experience" :key="'exp'+index" class="dynamic-block">
                  <div class="block-top">
                    <span class="block-badge">Role {{ index + 1 }}</span>
                    <button type="button" class="btn-remove" @click="removeExperience(index)" title="Remove">✕</button>
                  </div>
                  <div class="input-grid-3">
                    <div class="input-group"><label>Job Title</label><input v-model="exp.role" placeholder="Senior Engineer" /></div>
                    <div class="input-group"><label>Company</label><input v-model="exp.company" placeholder="Stripe" /></div>
                    <div class="input-group"><label>Duration</label><input v-model="exp.duration" placeholder="2021 – Present" /></div>
                  </div>
                  <div class="input-group mt-2">
                    <label>Brief Description <span class="label-hint">AI adds metrics & impact</span></label>
                    <textarea v-model="exp.description" rows="2" placeholder="Led payment gateway migration, improved API latency, managed 4 engineers..."></textarea>
                  </div>
                </div>
              </transition-group>
            </section>

            <!-- ── Projects ── -->
            <section class="form-section">
              <div class="section-label">
                <span class="section-num">03</span>
                <h3>Projects</h3>
                <button type="button" class="btn-add" @click="addProject">+ Add Project</button>
              </div>
              <transition-group name="block-anim" tag="div">
                <div v-for="(proj, index) in formData.projects" :key="'proj'+index" class="dynamic-block">
                  <div class="block-top">
                    <span class="block-badge">Project {{ index + 1 }}</span>
                    <button type="button" class="btn-remove" @click="removeProject(index)">✕</button>
                  </div>
                  <div class="input-grid-2">
                    <div class="input-group"><label>Project Name</label><input v-model="proj.name" placeholder="Distributed Cache System" /></div>
                    <div class="input-group"><label>Tech Stack</label><input v-model="proj.tech" placeholder="Go, Redis, gRPC" /></div>
                  </div>
                  <div class="input-group mt-2">
                    <label>Brief Description</label>
                    <textarea v-model="proj.description" rows="2" placeholder="Built a caching layer for high-frequency trading data..."></textarea>
                  </div>
                </div>
              </transition-group>
            </section>

            <!-- ── Education ── -->
            <section class="form-section">
              <div class="section-label">
                <span class="section-num">04</span>
                <h3>Education</h3>
                <button type="button" class="btn-add" @click="addEducation">+ Add Education</button>
              </div>
              <transition-group name="block-anim" tag="div">
                <div v-for="(edu, index) in formData.education" :key="'edu'+index" class="dynamic-block">
                  <div class="block-top">
                    <span class="block-badge">Education {{ index + 1 }}</span>
                    <button type="button" class="btn-remove" @click="removeEducation(index)">✕</button>
                  </div>
                  <div class="input-grid-3">
                    <div class="input-group"><label>Degree</label><input v-model="edu.degree" placeholder="B.S. Computer Science" /></div>
                    <div class="input-group"><label>Institution</label><input v-model="edu.school" placeholder="MIT" /></div>
                    <div class="input-group"><label>Year</label><input v-model="edu.year" placeholder="2020" /></div>
                  </div>
                </div>
              </transition-group>
            </section>

            <!-- ── Target ── -->
            <section class="form-section">
              <div class="section-label">
                <span class="section-num">05</span>
                <h3>Target Alignment</h3>
              </div>
              <div class="input-group">
                <label>Target Role / Company <span class="label-hint">Optional — AI tailors tone</span></label>
                <input v-model="formData.target_company" placeholder="Staff Engineer at OpenAI" />
              </div>
            </section>

            <!-- Sticky submit bar -->
            <div class="form-footer">
              <div class="footer-inner">
                <div class="footer-hint">Your data is processed securely and never stored.</div>
                <div class="footer-actions">
                  <button type="submit" class="btn-generate" :disabled="isGenerating">
                    <span v-if="!isGenerating">Generate Elite CV →</span>
                    <span v-else>Synthesizing…</span>
                  </button>
                </div>
              </div>
            </div>

          </form>
        </div>

        <!-- ══════════════════════════════════════════
             3. GENERATING (3D LOADER)
        ══════════════════════════════════════════ -->
        <div v-else-if="view === 'generating'" class="view-container loader-view" key="generating">
          <div class="loader-stage">

            <!-- 3D rotating document -->
            <div class="doc-scene">
              <div class="doc-cube">
                <div class="doc-face doc-front">
                  <div class="doc-lines">
                    <div class="dl dl-h"></div>
                    <div class="dl dl-m"></div>
                    <div class="dl dl-m"></div>
                    <div class="dl dl-s"></div>
                    <div class="dl dl-m"></div>
                    <div class="dl dl-s"></div>
                  </div>
                </div>
                <div class="doc-face doc-back">
                  <div class="doc-lines">
                    <div class="dl dl-m"></div>
                    <div class="dl dl-s"></div>
                    <div class="dl dl-m"></div>
                  </div>
                </div>
                <div class="doc-face doc-right"></div>
                <div class="doc-face doc-left"></div>
                <div class="doc-face doc-top"></div>
                <div class="doc-face doc-bottom"></div>
              </div>
            </div>

            <!-- Orbiting rings -->
            <div class="orbit-ring orbit-1">
              <div class="orbit-dot"></div>
            </div>
            <div class="orbit-ring orbit-2">
              <div class="orbit-dot"></div>
            </div>

            <!-- Scanning beam -->
            <div class="scan-beam"></div>

          </div>

          <div class="loader-text-block">
            <h2 class="loader-headline">{{ loaderPhase }}</h2>
            <div class="loader-steps">
              <div v-for="(step, i) in loaderSteps" :key="i" class="lstep" :class="{ done: i < loaderStep, active: i === loaderStep }">
                <span class="lstep-icon">{{ i < loaderStep ? '✓' : (i === loaderStep ? '◌' : '○') }}</span>
                <span>{{ step }}</span>
              </div>
            </div>
            <div class="loader-bar-wrap">
              <div class="loader-bar-fill" :style="{ width: loaderProgress + '%' }"></div>
            </div>
          </div>
        </div>

        <!-- ══════════════════════════════════════════
             4. DONE
        ══════════════════════════════════════════ -->
        <div v-else-if="view === 'done'" class="view-container done-view" key="done">
          <div class="done-icon-wrap">
            <div class="done-ring"></div>
            <div class="done-check">✓</div>
          </div>
          <h2 class="done-headline">CV Engineered Successfully</h2>
          <p class="done-sub">Your ATS-optimized PDF is ready. It has been tailored with metrics, keywords, and Harvard formatting.</p>
          <div class="done-actions">
            <button class="btn-download" @click="downloadFile">
              <span>⬇</span> Download PDF
            </button>
            <button class="btn-edit" @click="view = 'form'">Edit & Regenerate</button>
          </div>
          <div class="done-stats">
            <div class="dstat"><span class="dstat-val">94</span><span class="dstat-key">ATS Score</span></div>
            <div class="dstat"><span class="dstat-val">Harvard</span><span class="dstat-key">Format</span></div>
            <div class="dstat"><span class="dstat-val">PDF</span><span class="dstat-key">Ready</span></div>
          </div>
        </div>

      </transition>
    </main>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, onBeforeUnmount, watch } from 'vue';

const view = ref('landing');
const isGenerating = ref(false);
const generatedPdfBlob = ref(null);
const particleCanvas = ref(null);

// ── Loader state ──
const loaderStep = ref(0);
const loaderProgress = ref(0);
const loaderSteps = [
  'Parsing your career data',
  'Expanding with AI metrics',
  'Applying Harvard formatting',
  'Injecting ATS keywords',
  'Generating PDF',
];
const loaderPhases = ['Analyzing...', 'Expanding...', 'Formatting...', 'Optimizing...', 'Compiling...'];
const loaderPhase = ref(loaderPhases[0]);
let loaderInterval = null;

watch(view, (v) => {
  if (v === 'generating') startLoaderAnimation();
  else stopLoaderAnimation();
});

function startLoaderAnimation() {
  stopLoaderAnimation(); // clear any existing interval first
  loaderStep.value = 0;
  loaderProgress.value = 0;
  loaderPhase.value = loaderPhases[0];
  let step = 0;
  loaderInterval = setInterval(() => {
    if (step < loaderSteps.length - 1) {
      step++;
      loaderStep.value = step;
      loaderPhase.value = loaderPhases[step] || loaderPhases[loaderPhases.length - 1];
      loaderProgress.value = Math.round((step / (loaderSteps.length - 1)) * 80); // cap at 80% — API call fills the rest
    }
  }, 1400);
}

function stopLoaderAnimation() {
  if (loaderInterval) { clearInterval(loaderInterval); loaderInterval = null; }
}

// ── Form data ──
const formData = reactive({
  name: '', email: '', phone: '', links: '', summary: '', skills: '',
  experience: [{ role: '', company: '', duration: '', description: '' }],
  projects: [{ name: '', tech: '', description: '' }],
  education: [{ degree: '', school: '', year: '' }],
  target_company: ''
});

const addExperience = () => formData.experience.push({ role: '', company: '', duration: '', description: '' });
const removeExperience = (i) => formData.experience.splice(i, 1);
const addProject = () => formData.projects.push({ name: '', tech: '', description: '' });
const removeProject = (i) => formData.projects.splice(i, 1);
const addEducation = () => formData.education.push({ degree: '', school: '', year: '' });
const removeEducation = (i) => formData.education.splice(i, 1);

const fillDummyData = () => {
  formData.name = "Alexander Mercer";
  formData.email = "alex.mercer@email.com";
  formData.phone = "+1 (555) 019-2834";
  formData.links = "linkedin.com/in/alexmercer | github.com/alexm-dev";
  formData.summary = "Senior Software Engineer specializing in distributed systems and cloud architecture. Proven track record of scaling applications.";
  formData.skills = "Python, Go, TypeScript, React, Vue, AWS, Kubernetes, Docker, PostgreSQL, Redis";
  // Use splice to preserve Vue 3 reactivity on the array references
  formData.experience.splice(0, formData.experience.length,
    { role: "Senior Backend Engineer", company: "Stripe", duration: "2021 - Present", description: "Led the payment gateway migration. Improved API latency. Managed a team of 4 engineers." },
    { role: "Software Engineer II", company: "Twilio", duration: "2018 - 2021", description: "Built microservices for messaging platform. Reduced server costs. Implemented CI/CD pipelines." }
  );
  formData.projects.splice(0, formData.projects.length,
    { name: "Distributed Cache System", tech: "Go, Redis, gRPC", description: "Built a custom caching layer for high-frequency trading data." },
    { name: "NexCV AI", tech: "Vue 3, Flask, Groq LLM", description: "Developed an AI resume builder that bypasses ATS systems." }
  );
  formData.education.splice(0, formData.education.length,
    { degree: "B.S. Computer Science", school: "University of Washington", year: "2018" }
  );
  formData.target_company = "Staff Engineer at OpenAI";
};

const submitForm = async () => {
  view.value = 'generating';
  isGenerating.value = true;
  try {
    const response = await fetch('http://localhost:5000/api/generate/form', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(formData)
    });
    if (!response.ok) {
      const err = await response.json();
      throw new Error(err.error || "Server Error");
    }
    generatedPdfBlob.value = await response.blob();
    loaderProgress.value = 100;
    loaderStep.value = loaderSteps.length;
    setTimeout(() => { view.value = 'done'; }, 600);
  } catch (error) {
    console.error(error);
    alert(`Error: ${error.message}`);
    view.value = 'form';
  } finally {
    isGenerating.value = false;
  }
};

const downloadFile = () => {
  if (!generatedPdfBlob.value) return;
  const url = window.URL.createObjectURL(generatedPdfBlob.value);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${formData.name.replace(/\s+/g, '_')}_CV.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.URL.revokeObjectURL(url);
};

// ── Particle system ──
let animFrame = null;
let particles = [];
let resizeHandler = null;

function initParticles() {
  const canvas = particleCanvas.value;
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  resizeHandler = () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  };
  resizeHandler();
  window.addEventListener('resize', resizeHandler);

  const count = Math.min(60, Math.floor(window.innerWidth / 20));
  particles = Array.from({ length: count }, () => ({
    x: Math.random() * canvas.width,
    y: Math.random() * canvas.height,
    vx: (Math.random() - 0.5) * 0.3,
    vy: (Math.random() - 0.5) * 0.3,
    r: Math.random() * 1.5 + 0.5,
    a: Math.random() * 0.5 + 0.1,
  }));

  const draw = () => {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    particles.forEach(p => {
      p.x += p.vx; p.y += p.vy;
      if (p.x < 0) p.x = canvas.width;
      if (p.x > canvas.width) p.x = 0;
      if (p.y < 0) p.y = canvas.height;
      if (p.y > canvas.height) p.y = 0;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(255,255,255,${p.a})`;
      ctx.fill();
    });
    // Draw connecting lines
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x;
        const dy = particles[i].y - particles[j].y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < 120) {
          ctx.beginPath();
          ctx.moveTo(particles[i].x, particles[i].y);
          ctx.lineTo(particles[j].x, particles[j].y);
          ctx.strokeStyle = `rgba(255,255,255,${0.08 * (1 - dist / 120)})`;
          ctx.lineWidth = 0.5;
          ctx.stroke();
        }
      }
    }
    animFrame = requestAnimationFrame(draw);
  };
  draw();
}

onMounted(() => { initParticles(); });
onBeforeUnmount(() => {
  if (animFrame) cancelAnimationFrame(animFrame);
  if (resizeHandler) window.removeEventListener('resize', resizeHandler);
  stopLoaderAnimation();
});
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Syne:wght@600;700;800&family=Outfit:wght@300;400;500;600&display=swap');

:root {
  --black:     #020202;
  --surface:   #0c0c0e;
  --elevated:  #141418;
  --border:    #222228;
  --border-hi: #3a3a44;
  --text:      #f0f0f2;
  --muted:     #6b6b78;
  --accent:    #e2e2ff;
  --accent2:   #9b8fff;
  --accent3:   #5f5ae8;
  --glow:      rgba(155, 143, 255, 0.18);
  --rad:       10px;
  --ease:      cubic-bezier(0.4, 0, 0.2, 1);
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html, body { background: #020202; }

/* Vite scaffolds #app with max-width and text-align:center — reset both */
#app {
  width: 100%;
  max-width: 100% !important;
  margin: 0 !important;
  padding: 0 !important;
  text-align: center !important;
}

/* All keyframes global so Vue scoped hashing doesn't break animation references */
@keyframes revealUp {
  to { opacity: 1; transform: translateY(0); }
}
@keyframes pulseGlow {
  0%, 100% { box-shadow: 0 0 4px var(--accent2); opacity: 1; }
  50%       { box-shadow: 0 0 12px var(--accent2); opacity: 0.6; }
}
@keyframes shimmer {
  0%        { transform: translateX(-100%); }
  60%, 100% { transform: translateX(150%); }
}
@keyframes floatCard {
  0%, 100% { transform: translateY(0); }
  50%      { transform: translateY(-8px); }
}
@keyframes barGrow {
  from { transform: scaleX(0); }
  to   { transform: scaleX(1); }
}
@keyframes rotateBorder { to { transform: rotate(360deg); } }
@keyframes spinDoc {
  0%   { transform: rotateX(10deg) rotateY(0deg); }
  25%  { transform: rotateX(5deg) rotateY(90deg); }
  50%  { transform: rotateX(10deg) rotateY(180deg); }
  75%  { transform: rotateX(5deg) rotateY(270deg); }
  100% { transform: rotateX(10deg) rotateY(360deg); }
}
@keyframes dlPulse {
  0%, 100% { opacity: 0.4; }
  50%      { opacity: 1; }
}
@keyframes orbitSpin { to { transform: rotate(360deg); } }
@keyframes scanDown {
  0%   { top: 40px; opacity: 0; }
  10%  { opacity: 1; }
  90%  { opacity: 1; }
  100% { top: 160px; opacity: 0; }
}
@keyframes expandRing {
  from { transform: scale(0); opacity: 0; }
  to   { transform: scale(1); opacity: 1; }
}
@keyframes popIn {
  from { transform: scale(0); opacity: 0; }
  to   { transform: scale(1); opacity: 1; }
}
@keyframes spin { to { transform: rotate(360deg); } }
</style>

<style scoped>

/* ══════════════════════════════════════════
   LAYOUT
══════════════════════════════════════════ */
.app-container {
  min-height: 100vh;
  width: 100%;
  background: var(--black);
  color: var(--text);
  font-family: 'Outfit', sans-serif;
  display: flex;
  flex-direction: column;
  align-items: stretch;
  padding: 0 0 6rem;
  position: relative;
  overflow-x: hidden;
}

.particle-canvas {
  position: fixed;
  inset: 0;
  z-index: 0;
  pointer-events: none;
}

.grid-overlay {
  position: fixed;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background-image:
    linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px);
  background-size: 60px 60px;
  mask-image: radial-gradient(ellipse 80% 80% at 50% 0%, black 40%, transparent 100%);
}

.content-wrapper { 
  position: relative; 
  z-index: 10; 
  width: 100%; 
  max-width: 100%; 
  padding: 0 2rem; 
  margin: 0 auto; 
  box-sizing: border-box; 
  display: flex; 
  flex-direction: column; 
  align-items: center; }

.view-container { width: 100%; }

/* ══════════════════════════════════════════
   VIEW TRANSITIONS
══════════════════════════════════════════ */
.view-transition-enter-active { transition: opacity 0.45s var(--ease), transform 0.45s var(--ease); }
.view-transition-leave-active { transition: opacity 0.25s var(--ease), transform 0.25s var(--ease); }
.view-transition-enter-from  { opacity: 0; transform: translateY(16px); }
.view-transition-leave-to    { opacity: 0; transform: translateY(-8px); }

/* ══════════════════════════════════════════
   LANDING — NAV
══════════════════════════════════════════ */
.landing-view { 
  padding-top: 2rem; 
  width: 100%; 
  display: flex; 
  flex-direction: column; 
  align-items: center; 
  text-align: center; }

.top-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 0 2rem;
  width: 100%;
}
.nav-logo {
  display: flex;
  align-items: center;
  gap: 8px;
  font-family: 'Syne', sans-serif;
  font-weight: 700;
  font-size: 1.1rem;
  letter-spacing: -0.03em;
}
.logo-dot {
  width: 8px; height: 8px;
  border-radius: 50%;
  background: var(--accent2);
  box-shadow: 0 0 10px var(--accent2);
}
.nav-version {
  font-size: 0.7rem;
  color: var(--muted);
  font-family: 'DM Mono', monospace;
  background: var(--elevated);
  border: 1px solid var(--border);
  padding: 2px 7px;
  border-radius: 20px;
}
.nav-tag {
  font-size: 0.78rem;
  color: var(--muted);
  font-family: 'DM Mono', monospace;
  border: 1px solid var(--border);
  padding: 5px 12px;
  border-radius: 20px;
}

/* ── Line reveal animation ── */
.line-reveal {
  display: block;
  opacity: 0;
  transform: translateY(20px);
  animation: revealUp 0.7s var(--ease) forwards;
  animation-delay: var(--delay, 0s);
}
/* ══════════════════════════════════════════
   LANDING — HERO
══════════════════════════════════════════ */

.hero-section { padding: 2rem 0 3rem; }
.hero-section { 
  padding: 2rem 0 3rem; 
  display: flex; 
  flex-direction: column; 
  align-items: center; 
  text-align: center; 
  width: 100%; }
.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 0.72rem;
  font-family: 'DM Mono', monospace;
  color: var(--accent2);
  border: 1px solid rgba(155, 143, 255, 0.3);
  background: rgba(155, 143, 255, 0.07);
  padding: 6px 14px;
  border-radius: 20px;
  margin-bottom: 2rem;
  letter-spacing: 0.05em;
  opacity: 0;
  animation: revealUp 0.6s var(--ease) 0s forwards;
}
.badge-pulse {
  width: 6px; height: 6px;
  border-radius: 50%;
  background: var(--accent2);
  animation: pulseGlow 2s ease-in-out infinite;
}
.hero-headline {
  font-family: 'Syne', sans-serif;
  font-weight: 800;
  font-size: clamp(2.8rem, 7vw, 5.5rem);
  line-height: 1.05;
  letter-spacing: -0.04em;
  margin-bottom: 1.5rem;
}
.gradient-line {
  background: linear-gradient(135deg, #fff 20%, var(--accent2) 60%, var(--accent3) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-sub {
  font-size: clamp(1rem, 2vw, 1.2rem);
  color: var(--muted);
  max-width: 520px;
  line-height: 1.7;
  margin-bottom: 2rem;
}

/* ── Feature chips ── */
.feature-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 2.5rem;
  justify-content: center;
}
.chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 0.8rem;
  color: var(--muted);
  border: 1px solid var(--border);
  padding: 5px 12px;
  border-radius: 20px;
  transition: all 0.2s;
}
.chip:hover { border-color: var(--border-hi); color: var(--text); }
.chip-icon { font-size: 0.65rem; color: var(--accent2); }

/* ── CTA ── */
.cta-block {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  flex-wrap: wrap;
  justify-content: center;
}
.cta-primary {
  position: relative;
  display: inline-flex;
  align-items: center;
  gap: 10px;
  background: #fff;
  color: #000;
  border: none;
  padding: 0.9rem 2rem;
  border-radius: var(--rad);
  font-family: 'Outfit', sans-serif;
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  overflow: hidden;
  transition: transform 0.2s, box-shadow 0.2s;
}
.cta-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 40px rgba(255,255,255,0.18);
}
.cta-primary:active { transform: translateY(0); }
.cta-shimmer {
  position: absolute;
  inset: 0;
  background: linear-gradient(105deg, transparent 40%, rgba(255,255,255,0.4) 50%, transparent 60%);
  transform: translateX(-100%);
  animation: shimmer 3s ease-in-out infinite;
}
.cta-arrow { font-size: 1.1rem; transition: transform 0.2s; }
.cta-primary:hover .cta-arrow { transform: translateX(4px); }
.cta-note { font-size: 0.8rem; color: var(--muted); }

/* ══════════════════════════════════════════
   LANDING — PREVIEW CARD
══════════════════════════════════════════ */
.preview-float {
  position: relative;
  margin: 3rem 0;
  display: flex;
  justify-content: center;
}
.preview-card {
  background: var(--elevated);
  border: 1px solid var(--border-hi);
  border-radius: 16px;
  padding: 1.5rem;
  width: 100%;
  max-width: 480px;
  position: relative;
  z-index: 2;
  animation: floatCard 4s ease-in-out infinite;
}
.preview-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 1rem;
}
.preview-avatar {
  width: 44px; height: 44px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--accent3), var(--accent2));
  display: flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 0.9rem; color: #fff;
  flex-shrink: 0;
}
.preview-name { font-weight: 600; font-size: 1rem; }
.preview-role { font-size: 0.8rem; color: var(--muted); }
.preview-score { margin-left: auto; display: flex; flex-direction: column; align-items: center; gap: 2px; }
.score-ring { position: relative; width: 44px; height: 44px; }
.ring-svg { width: 100%; height: 100%; transform: rotate(-90deg); }
.score-num {
  position: absolute; inset: 0; display: flex; align-items: center; justify-content: center;
  font-size: 0.75rem; font-weight: 700; font-family: 'DM Mono', monospace;
}
.score-label { font-size: 0.65rem; color: var(--muted); font-family: 'DM Mono', monospace; }

.preview-skills {
  display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 1rem;
}
.skill-tag {
  font-size: 0.72rem; padding: 3px 10px; border-radius: 20px;
  border: 1px solid var(--border); color: var(--muted);
  font-family: 'DM Mono', monospace;
}
.skill-tag.active { border-color: var(--accent2); color: var(--accent2); background: rgba(155,143,255,0.08); }

.preview-bars { display: flex; flex-direction: column; gap: 8px; }
.bar-row {
  display: flex; align-items: center; gap: 10px;
  font-size: 0.75rem; color: var(--muted);
}
.bar-row span { width: 70px; flex-shrink: 0; }
.bar-track {
  flex: 1; height: 4px; background: var(--border); border-radius: 2px; overflow: hidden;
}
.bar-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--accent3), var(--accent2));
  border-radius: 2px;
  animation: barGrow 1.5s var(--ease) 1.2s both;
  transform-origin: left;
}
.preview-glow {
  position: absolute;
  inset: -1px; border-radius: 17px;
  background: conic-gradient(from 180deg, var(--accent3), var(--accent2), transparent, var(--accent3));
  z-index: 1;
  opacity: 0.3;
  animation: rotateBorder 6s linear infinite;
  mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
  mask-composite: exclude;
  padding: 1px;
}
/* ══════════════════════════════════════════
   LANDING — STATS
══════════════════════════════════════════ */
.stats-row {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0;
  border: 1px solid var(--border);
  border-radius: var(--rad);
  overflow: hidden;
  max-width: 480px;
  margin: 0 auto;
}
.stat-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 1.2rem 1rem;
  gap: 4px;
}
.stat-num {
  font-family: 'Syne', sans-serif;
  font-weight: 700;
  font-size: 1.5rem;
  color: var(--text);
  letter-spacing: -0.03em;
}
.stat-label { font-size: 0.72rem; color: var(--muted); }
.stat-divider { width: 1px; height: 40px; background: var(--border); }

/* ══════════════════════════════════════════
   FORM VIEW
══════════════════════════════════════════ */
.form-view { padding-top: 1.5rem; }

.form-topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 0 1.5rem;
  border-bottom: 1px solid var(--border);
  margin-bottom: 2rem;
}
.back-btn {
  background: none; border: none; color: var(--muted);
  font-family: 'Outfit', sans-serif; font-size: 0.9rem;
  cursor: pointer; display: flex; align-items: center; gap: 6px;
  transition: color 0.2s;
}
.back-btn:hover { color: var(--text); }
.back-arrow { font-size: 1.1rem; }

.form-progress {
  display: flex; flex-direction: column; align-items: center; gap: 6px;
}
.progress-label { font-size: 0.75rem; color: var(--muted); font-family: 'DM Mono', monospace; }
.progress-dots { display: flex; gap: 5px; }
.pdot {
  width: 22px; height: 4px; border-radius: 2px;
  background: var(--border); transition: background 0.3s;
}
.top-nav { display: flex; 
  justify-content: space-between; 
  align-items: center; 
  padding: 1rem 0 2rem; 
  width: 100%; }
.pdot.active { background: var(--accent2); }

.btn-load-demo {
  background: var(--elevated); border: 1px solid var(--border);
  color: var(--muted); font-family: 'Outfit', sans-serif;
  font-size: 0.82rem; padding: 6px 14px; border-radius: 6px;
  cursor: pointer; transition: all 0.2s;
}
.btn-load-demo:hover { border-color: var(--border-hi); color: var(--text); }

.form-hero-text { margin-bottom: 2.5rem; }
.form-hero-text h2 {
  font-family: 'Syne', sans-serif; font-weight: 700;
  font-size: clamp(1.8rem, 4vw, 2.5rem); letter-spacing: -0.03em;
  margin-bottom: 0.5rem;
}
.text-accent {
  background: linear-gradient(135deg, var(--accent2), var(--accent3));
  -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;
}
.form-hero-text p { color: var(--muted); font-size: 0.95rem; }

/* ── Form sections ── */
.form-section { margin-bottom: 3rem; }

.section-label {
  display: flex; align-items: center; gap: 12px;
  margin-bottom: 1.5rem;
}
.section-num {
  font-family: 'DM Mono', monospace; font-size: 0.7rem;
  color: var(--accent2); background: rgba(155,143,255,0.1);
  border: 1px solid rgba(155,143,255,0.25);
  padding: 3px 8px; border-radius: 4px;
}
.section-label h3 {
  font-family: 'Syne', sans-serif; font-weight: 600;
  font-size: 1.1rem; letter-spacing: -0.02em; flex: 1;
}

.btn-add {
  background: none; border: 1px dashed var(--border-hi);
  color: var(--muted); font-family: 'Outfit', sans-serif;
  font-size: 0.82rem; padding: 5px 12px; border-radius: 6px;
  cursor: pointer; transition: all 0.2s;
}
.btn-add:hover { border-color: var(--accent2); color: var(--accent2); }

/* ── Grids ── */
.input-grid-2 {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1rem;
}
.input-grid-3 {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
}
.mt-2 { margin-top: 0.75rem; }
.mt-3 { margin-top: 1rem; }

/* ── Input fields ── */
.input-group { display: flex; flex-direction: column; gap: 6px; }
.input-group label {
  font-size: 0.78rem; font-weight: 500;
  color: var(--muted); letter-spacing: 0.01em;
  display: flex; align-items: center; gap: 8px;
}
.label-hint {
  font-size: 0.7rem; color: var(--accent2);
  font-family: 'DM Mono', monospace; font-weight: 400;
}
.input-group input,
.input-group textarea {
  background: var(--elevated);
  border: 1px solid var(--border);
  color: var(--text);
  padding: 0.75rem 1rem;
  border-radius: 8px;
  font-family: 'Outfit', sans-serif;
  font-size: 0.92rem;
  transition: border-color 0.2s, box-shadow 0.2s;
  resize: vertical;
}
.input-group input::placeholder,
.input-group textarea::placeholder { color: rgba(107,107,120,0.5); }
.input-group input:focus,
.input-group textarea:focus {
  outline: none;
  border-color: var(--accent2);
  box-shadow: 0 0 0 3px rgba(155,143,255,0.1);
}

/* ── Dynamic blocks ── */
.dynamic-block {
  background: var(--elevated);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.25rem 1.5rem;
  margin-bottom: 1rem;
  transition: border-color 0.2s;
}
.dynamic-block:hover { border-color: var(--border-hi); }
.block-top {
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 1rem;
}
.block-badge {
  font-size: 0.72rem; font-family: 'DM Mono', monospace;
  color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em;
}
.btn-remove {
  background: none; border: none; color: var(--muted);
  font-size: 0.85rem; cursor: pointer; padding: 2px 6px;
  border-radius: 4px; transition: all 0.2s;
}
.btn-remove:hover { color: #ff5f5f; background: rgba(255,95,95,0.1); }

/* ── Block animations ── */
.block-anim-enter-active { transition: all 0.3s var(--ease); }
.block-anim-leave-active { transition: all 0.2s var(--ease); }
.block-anim-enter-from { opacity: 0; transform: translateY(-10px); }
.block-anim-leave-to   { opacity: 0; transform: translateY(10px); height: 0; padding: 0; margin: 0; overflow: hidden; }

/* ── Form footer ── */
.form-footer {
  position: sticky; bottom: 0;
  background: linear-gradient(transparent, var(--black) 30%);
  padding: 2rem 0 0;
  z-index: 50;
}
.footer-inner {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1rem 1.5rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  backdrop-filter: blur(12px);
}
.footer-hint { font-size: 0.78rem; color: var(--muted); }
.footer-actions { display: flex; gap: 0.75rem; }

.btn-generate {
  background: #fff; color: #000;
  border: none; padding: 0.8rem 1.75rem;
  border-radius: 8px; font-family: 'Outfit', sans-serif;
  font-weight: 600; font-size: 0.95rem;
  cursor: pointer; transition: all 0.2s; white-space: nowrap;
}
.btn-generate:hover:not(:disabled) {
  background: var(--accent);
  transform: translateY(-1px);
  box-shadow: 0 8px 24px rgba(255,255,255,0.2);
}
.btn-generate:disabled { opacity: 0.4; cursor: not-allowed; }

/* ══════════════════════════════════════════
   GENERATING VIEW — 3D LOADER
══════════════════════════════════════════ */
.loader-view {
  display: flex; flex-direction: column; align-items: center;
  justify-content: center; min-height: 80vh; gap: 3rem;
  padding-top: 4rem;
}

.loader-stage {
  position: relative;
  width: 200px; height: 200px;
  display: flex; align-items: center; justify-content: center;
  perspective: 600px;
}

/* 3D Document Cube */
.doc-scene {
  width: 90px; height: 120px;
  perspective: 600px;
  position: relative; z-index: 3;
}
.doc-cube {
  width: 100%; height: 100%;
  position: relative;
  transform-style: preserve-3d;
  animation: spinDoc 6s ease-in-out infinite;
}
.doc-face {
  position: absolute;
  width: 90px; height: 120px;
  border: 1px solid rgba(155,143,255,0.4);
  background: rgba(20,20,30,0.95);
  backface-visibility: hidden;
}
.doc-front  { transform: translateZ(6px); }
.doc-back   { transform: rotateY(180deg) translateZ(6px); }
.doc-right  { width: 12px; transform: rotateY(90deg) translateZ(39px); background: rgba(95,90,232,0.3); }
.doc-left   { width: 12px; transform: rotateY(-90deg) translateZ(39px); background: rgba(95,90,232,0.2); }
.doc-top    { height: 12px; transform: rotateX(90deg) translateZ(6px); background: rgba(95,90,232,0.25); }
.doc-bottom { height: 12px; transform: rotateX(-90deg) translateZ(114px); background: rgba(30,30,40,0.9); }

.doc-lines {
  padding: 12px 10px;
  display: flex; flex-direction: column; gap: 7px;
}
.dl {
  height: 5px; border-radius: 2px;
  background: rgba(155,143,255,0.3);
  animation: dlPulse 2s ease-in-out infinite;
}
.dl-h { width: 80%; background: rgba(155,143,255,0.7); animation-delay: 0s; }
.dl-m { width: 90%; animation-delay: 0.3s; }
.dl-s { width: 60%; animation-delay: 0.6s; }
/* Orbiting rings */
.orbit-ring {
  position: absolute; border-radius: 50%;
  border: 1px dashed rgba(155,143,255,0.2);
  animation: orbitSpin linear infinite;
}
.orbit-1 {
  width: 160px; height: 160px;
  animation-duration: 6s;
}
.orbit-2 {
  width: 200px; height: 200px;
  animation-duration: 10s;
  animation-direction: reverse;
  border-color: rgba(95,90,232,0.15);
}
.orbit-dot {
  position: absolute; top: -4px; left: 50%;
  width: 7px; height: 7px; border-radius: 50%;
  background: var(--accent2);
  box-shadow: 0 0 10px var(--accent2);
  transform: translateX(-50%);
}

/* Scan beam */
.scan-beam {
  position: absolute;
  left: 50%; top: 0;
  transform: translateX(-50%);
  width: 90px; height: 2px;
  background: linear-gradient(90deg, transparent, var(--accent2), transparent);
  animation: scanDown 2s ease-in-out infinite;
  z-index: 4;
  border-radius: 1px;
}
/* Loader text */
.loader-text-block { text-align: center; max-width: 360px; width: 100%; }
.loader-headline {
  font-family: 'Syne', sans-serif; font-weight: 700;
  font-size: 1.5rem; letter-spacing: -0.03em;
  margin-bottom: 1.5rem; color: var(--text);
}
.loader-steps {
  display: flex; flex-direction: column; gap: 8px;
  margin-bottom: 1.5rem; text-align: left;
}
.lstep {
  display: flex; align-items: center; gap: 10px;
  font-size: 0.85rem; color: var(--muted); transition: color 0.3s;
}
.lstep.active { color: var(--accent2); }
.lstep.done   { color: var(--muted); text-decoration: line-through; opacity: 0.5; }
.lstep-icon {
  width: 18px; font-family: 'DM Mono', monospace; font-size: 0.75rem; flex-shrink: 0;
  color: var(--accent2);
}

.loader-bar-wrap {
  height: 3px; background: var(--border); border-radius: 2px; overflow: hidden;
}
.loader-bar-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--accent3), var(--accent2));
  border-radius: 2px;
  transition: width 1.2s var(--ease);
}

/* ══════════════════════════════════════════
   DONE VIEW
══════════════════════════════════════════ */
.done-view {
  display: flex; flex-direction: column; align-items: center;
  justify-content: center; min-height: 80vh; gap: 1.25rem;
  text-align: center; padding-top: 4rem;
}

.done-icon-wrap {
  position: relative; width: 90px; height: 90px;
  display: flex; align-items: center; justify-content: center;
  margin-bottom: 0.5rem;
}
.done-ring {
  position: absolute; inset: 0; border-radius: 50%;
  border: 2px solid var(--accent2);
  animation: expandRing 0.6s var(--ease) forwards;
}
.done-check {
  font-size: 2.5rem; color: var(--accent2);
  animation: popIn 0.5s var(--ease) 0.3s both;
}

.done-headline {
  font-family: 'Syne', sans-serif; font-weight: 700;
  font-size: clamp(1.6rem, 4vw, 2.2rem); letter-spacing: -0.03em;
}
.done-sub { font-size: 0.95rem; color: var(--muted); max-width: 420px; line-height: 1.6; }

.done-actions {
  display: flex; gap: 0.75rem; flex-wrap: wrap; justify-content: center;
}
.btn-download {
  background: #fff; color: #000; border: none;
  padding: 0.85rem 2rem; border-radius: 8px;
  font-family: 'Outfit', sans-serif; font-weight: 600;
  font-size: 0.95rem; cursor: pointer; transition: all 0.2s;
  display: flex; align-items: center; gap: 8px;
}
.btn-download:hover { transform: translateY(-2px); box-shadow: 0 10px 30px rgba(255,255,255,0.2); }
.btn-edit {
  background: transparent; color: var(--muted);
  border: 1px solid var(--border); padding: 0.85rem 1.5rem;
  border-radius: 8px; font-family: 'Outfit', sans-serif;
  font-size: 0.9rem; cursor: pointer; transition: all 0.2s;
}
.btn-edit:hover { border-color: var(--border-hi); color: var(--text); }

.done-stats {
  display: flex; gap: 0; border: 1px solid var(--border);
  border-radius: 10px; overflow: hidden; margin-top: 1rem;
}
.dstat {
  padding: 1rem 1.5rem;
  display: flex; flex-direction: column; align-items: center; gap: 4px;
  border-right: 1px solid var(--border);
}
.dstat:last-child { border-right: none; }
.dstat-val {
  font-family: 'Syne', sans-serif; font-weight: 700;
  font-size: 1.2rem; color: var(--accent2);
}
.dstat-key { font-size: 0.72rem; color: var(--muted); }

/* ══════════════════════════════════════════
   RESPONSIVE
══════════════════════════════════════════ */
@media (max-width: 1200px) {
  .content-wrapper { padding: 0 1.25rem; }
  .app-container { padding: 0 0 5rem; }
  .top-nav { padding: 0.75rem 0 1.5rem; }
  .nav-links { display: none; }
  .hero-section { padding: 1.5rem 0 2rem; }
  .form-topbar { flex-wrap: wrap; gap: 0.75rem; }
  .footer-inner { flex-direction: column; align-items: stretch; }
  .btn-generate { width: 100%; text-align: center; }
  .footer-hint { text-align: center; }
  .done-actions { flex-direction: column; }
  .btn-download, .btn-edit { width: 100%; justify-content: center; }
  .stats-row { max-width: 100%; }
  .preview-card { max-width: 100%; }
  .done-stats { flex-direction: column; }
  .dstat { border-right: none; border-bottom: 1px solid var(--border); }
  .dstat:last-child { border-bottom: none; }
  .loader-view { min-height: 70vh; }
}

@media (max-width: 380px) {
  .hero-headline { font-size: 2.2rem; }
  .feature-chips { display: none; }
}


</style>